version: '3.5'

services:
  web:
    container_name: nginx
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app

  app:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade heads && uvicorn main:app --host 0.0.0.0 --reload'
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
        - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: app_db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=storage
    volumes:
      - /opt/app_progress/pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: